=== SamuelRDuarte/PlaylistOnTheWeb/PlaylistOnTheWeb/files/example.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="root" type="rootType"/>
  <xs:complexType name="artistaType">
    <xs:sequence>
      <xs:element type="xs:string" name="nome"/>
      <xs:element type="xs:string" name="id"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="artistasType">
    <xs:sequence>
      <xs:element type="artistaType" name="artista"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="musicaType">
    <xs:sequence>
      <xs:element type="xs:string" name="nome"/>
      <xs:element type="xs:string" name="id">
      <xs:element type="xs:string" name="externalUrl"/>
      <xs:element type="xs:string" name="img"/>
      <xs:element type="artistasType" name="artistas"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="musicasType">
    <xs:sequence>
      <xs:element type="musicaType" name="musica"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="playlistDemoType">
    <xs:sequence>
      <xs:element type="xs:string" name="nome"/>
      <xs:element name="id">
        <xs:restriction base="xs:integer">
            <xs:minInclusive value="1"/>
        </xs:restriction>
      </xs:element>
      <xs:element type="xs:string" name="numeroDeMusicas">
        <xs:restriction base="xs:integer">
            <xs:minInclusive value="1"/>
        </xs:restriction>
      </xs:element>
      <xs:element type="xs:date" name="dataCriacao" />
      <xs:element type="musicasType" name="musicas"/>
    </xs:sequence>
    <xs:attribute name="id">
      <xs:restriction base="xs:integer">
        <xs:minInclusive value="1"/>
      </xs:restriction>
    </xs:attribute>
  </xs:complexType>
  <xs:complexType name="rootType">
    <xs:sequence>
      <xs:element type="playlistDemoType" name="playlistDemo"/>
    </xs:sequence>
  </xs:complexType>
</xs:schema>

=== SamuelRDuarte/PlaylistOnTheWeb/PlaylistOnTheWeb/files/example.xml
<?xml version="1.0" encoding="utf-8"?>
<root xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  xsi:noNamespaceSchemaLocation="example.xsd">
    <playlistDemo id="1">
        <nome>Espanhol</nome>
        <id>1</id>
        <numeroDeMusicas>10</numeroDeMusicas>
        <dataCriacao>2020-11-13</dataCriacao>
        <musicas>
            <musica>
                <nome>Bolero</nome>
                <id>23sdfg678fd91</id>
                <externalUrl>https://open.spotify.com/artist/4GGm7CoOaCNFLMnFInNiMG</externalUrl>
                <img>https://i.scdn.co/image/ab67616d00004851a737ec66a9ef6c6d817a7756</img>
                <artistas>
                    <artista>
                        <nome>Auria</nome>
                        <id>23sdfg678fd91</id>
                    </artista>
                </artistas>
            </musica>
        </musicas>
    </playlistDemo>
</root>
